# Generated by Django 5.2.16 on 2026-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
